///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTestDemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestDemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("63420ca7-8589-43d7-88f7-8cf050cf6002")]
    public partial class MyTestDemoRepository : RepoGenBaseFolder
    {
        static MyTestDemoRepository instance = new MyTestDemoRepository();
        MyTestDemoRepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        MyTestDemoRepositoryFolders.List1000AppFolder _list1000;

        /// <summary>
        /// Gets the singleton class instance representing the MyTestDemoRepository element repository.
        /// </summary>
        [RepositoryFolder("63420ca7-8589-43d7-88f7-8cf050cf6002")]
        public static MyTestDemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestDemoRepository() 
            : base("MyTestDemoRepository", "/", null, 0, false, "63420ca7-8589-43d7-88f7-8cf050cf6002", ".\\RepositoryImages\\MyTestDemoRepository63420ca7.rximgres")
        {
            _rxmainframe = new MyTestDemoRepositoryFolders.RxMainFrameAppFolder(this);
            _list1000 = new MyTestDemoRepositoryFolders.List1000AppFolder(this);
        }

#region Variables

        string _lstItem = "Project Management";

        /// <summary>
        /// Gets or sets the value of variable lstItem.
        /// </summary>
        [TestVariable("e49d9783-8597-4398-9376-f933573bd101")]
        public string lstItem
        {
            get { return _lstItem; }
            set { _lstItem = value; }
        }

        string _itemEntry = "lblNumberOfPersonsNumber";

        /// <summary>
        /// Gets or sets the value of variable itemEntry.
        /// </summary>
        [TestVariable("00be462e-754e-4640-a8ac-e16a1c10deef")]
        public string itemEntry
        {
            get { return _itemEntry; }
            set { _itemEntry = value; }
        }

        string _intAge = "40";

        /// <summary>
        /// Gets or sets the value of variable intAge.
        /// </summary>
        [TestVariable("ac91a81b-075b-4827-a450-6c7be45f9614")]
        public string intAge
        {
            get { return _intAge; }
            set { _intAge = value; }
        }

        string _selectGender = "rdbFemale";

        /// <summary>
        /// Gets or sets the value of variable selectGender.
        /// </summary>
        [TestVariable("abc06e86-b5b0-4fcc-820f-fd7d3236b9f8")]
        public string selectGender
        {
            get { return _selectGender; }
            set { _selectGender = value; }
        }

        string _varLastName = "kumar";

        /// <summary>
        /// Gets or sets the value of variable varLastName.
        /// </summary>
        [TestVariable("b5a79d5e-4179-400a-9f17-737e0a22bd63")]
        public string varLastName
        {
            get { return _varLastName; }
            set { _varLastName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("63420ca7-8589-43d7-88f7-8cf050cf6002")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("06935d01-631c-4256-ae1a-01aae74ac790")]
        public virtual MyTestDemoRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("75aa4672-8463-4e56-8316-3af2ded735bb")]
        public virtual MyTestDemoRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestDemoRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("06935d01-631c-4256-ae1a-01aae74ac790")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            MyTestDemoRepositoryFolders.RxTabStandardFolder _rxtabstandard;
            RepoItemInfo _testdatabaseInfo;
            RepoItemInfo _btnaddpersonInfo;
            RepoItemInfo _lblnumberofpersonsnumberInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "06935d01-631c-4256-ae1a-01aae74ac790", "")
            {
                _rxtabstandard = new MyTestDemoRepositoryFolders.RxTabStandardFolder(this);
                _testdatabaseInfo = new RepoItemInfo(this, "TestDatabase", "?/?/tabpage[@accessiblename='Test database']", 30000, null, "c30d6034-ca86-42b1-b725-fa8dcf1b667b");
                _btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", "?/?/tabpage[@controlname='RxTabStandard']/button[@controlname='btnAddPerson']", 30000, null, "3d482371-5796-4466-8e7b-e930612d4981");
                _lblnumberofpersonsnumberInfo = new RepoItemInfo(this, "LblNumberOfPersonsNumber", "?/?/tabpage[@controlname='RxTabStandard']/text[@controlname='lblNumberOfPersonsNumber']", 30000, null, "cd9c97c3-5f8f-4ceb-ae44-4e2ec71dab61");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("06935d01-631c-4256-ae1a-01aae74ac790")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("06935d01-631c-4256-ae1a-01aae74ac790")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TestDatabase item.
            /// </summary>
            [RepositoryItem("c30d6034-ca86-42b1-b725-fa8dcf1b667b")]
            public virtual Ranorex.TabPage TestDatabase
            {
                get
                {
                    return _testdatabaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TestDatabase item info.
            /// </summary>
            [RepositoryItemInfo("c30d6034-ca86-42b1-b725-fa8dcf1b667b")]
            public virtual RepoItemInfo TestDatabaseInfo
            {
                get
                {
                    return _testdatabaseInfo;
                }
            }

            /// <summary>
            /// The BtnAddPerson item.
            /// </summary>
            [RepositoryItem("3d482371-5796-4466-8e7b-e930612d4981")]
            public virtual Ranorex.Button BtnAddPerson
            {
                get
                {
                    return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddPerson item info.
            /// </summary>
            [RepositoryItemInfo("3d482371-5796-4466-8e7b-e930612d4981")]
            public virtual RepoItemInfo BtnAddPersonInfo
            {
                get
                {
                    return _btnaddpersonInfo;
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item.
            /// </summary>
            [RepositoryItem("cd9c97c3-5f8f-4ceb-ae44-4e2ec71dab61")]
            public virtual Ranorex.Text LblNumberOfPersonsNumber
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item info.
            /// </summary>
            [RepositoryItemInfo("cd9c97c3-5f8f-4ceb-ae44-4e2ec71dab61")]
            public virtual RepoItemInfo LblNumberOfPersonsNumberInfo
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo;
                }
            }

            /// <summary>
            /// The RxTabStandard folder.
            /// </summary>
            [RepositoryFolder("69d6b1d4-1125-49ef-a249-64b27f7c8fdf")]
            public virtual MyTestDemoRepositoryFolders.RxTabStandardFolder RxTabStandard
            {
                get { return _rxtabstandard; }
            }
        }

        /// <summary>
        /// The RxTabStandardFolder folder.
        /// </summary>
        [RepositoryFolder("69d6b1d4-1125-49ef-a249-64b27f7c8fdf")]
        public partial class RxTabStandardFolder : RepoGenBaseFolder
        {
            RepoItemInfo _openInfo;
            RepoItemInfo _rdbfemaleInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _ageInfo;

            /// <summary>
            /// Creates a new RxTabStandard  folder.
            /// </summary>
            public RxTabStandardFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabStandard", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "69d6b1d4-1125-49ef-a249-64b27f7c8fdf", "")
            {
                _openInfo = new RepoItemInfo(this, "Open", "?/?/button[@accessiblename='Open']", 30000, null, "786dc92a-b0b3-46dd-a095-9ed54e7f352e");
                _rdbfemaleInfo = new RepoItemInfo(this, "RdbFemale", "?/?/radiobutton[@controltext=$selectGender]", 30000, null, "65113f6e-40d9-4a81-ab2d-2a2891e9e1a5");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", 30000, null, "288c8bf6-39de-42c6-a901-91904ceab920");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last name']", 30000, null, "40ac8158-aa2c-450e-b3d4-4914241fb9ec");
                _ageInfo = new RepoItemInfo(this, "Age", "?/?/text[@controlname='upDownEdit']", 30000, null, "53bf437c-2450-4133-bbe8-31abd3aa4368");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("69d6b1d4-1125-49ef-a249-64b27f7c8fdf")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("69d6b1d4-1125-49ef-a249-64b27f7c8fdf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("786dc92a-b0b3-46dd-a095-9ed54e7f352e")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("786dc92a-b0b3-46dd-a095-9ed54e7f352e")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The RdbFemale item.
            /// </summary>
            [RepositoryItem("65113f6e-40d9-4a81-ab2d-2a2891e9e1a5")]
            public virtual Ranorex.RadioButton RdbFemale
            {
                get
                {
                    return _rdbfemaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbFemale item info.
            /// </summary>
            [RepositoryItemInfo("65113f6e-40d9-4a81-ab2d-2a2891e9e1a5")]
            public virtual RepoItemInfo RdbFemaleInfo
            {
                get
                {
                    return _rdbfemaleInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("288c8bf6-39de-42c6-a901-91904ceab920")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("288c8bf6-39de-42c6-a901-91904ceab920")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("40ac8158-aa2c-450e-b3d4-4914241fb9ec")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("40ac8158-aa2c-450e-b3d4-4914241fb9ec")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Age item.
            /// </summary>
            [RepositoryItem("53bf437c-2450-4133-bbe8-31abd3aa4368")]
            public virtual Ranorex.Text Age
            {
                get
                {
                    return _ageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Age item info.
            /// </summary>
            [RepositoryItemInfo("53bf437c-2450-4133-bbe8-31abd3aa4368")]
            public virtual RepoItemInfo AgeInfo
            {
                get
                {
                    return _ageInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("75aa4672-8463-4e56-8316-3af2ded735bb")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _projectmanagementInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "75aa4672-8463-4e56-8316-3af2ded735bb", "")
            {
                _projectmanagementInfo = new RepoItemInfo(this, "ProjectManagement", "listitem[@text=$lstItem]", 30000, null, "2e328bba-6466-49fd-a849-2d1c3884f235");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("75aa4672-8463-4e56-8316-3af2ded735bb")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("75aa4672-8463-4e56-8316-3af2ded735bb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProjectManagement item.
            /// </summary>
            [RepositoryItem("2e328bba-6466-49fd-a849-2d1c3884f235")]
            public virtual Ranorex.ListItem ProjectManagement
            {
                get
                {
                    return _projectmanagementInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ProjectManagement item info.
            /// </summary>
            [RepositoryItemInfo("2e328bba-6466-49fd-a849-2d1c3884f235")]
            public virtual RepoItemInfo ProjectManagementInfo
            {
                get
                {
                    return _projectmanagementInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
